import { Message, Expert, Insight, FileType, Artifact } from "../shared/schema";
import { format } from "date-fns";

export function generateComprehensiveMarkdown(data: {
  conversation: { title: string; createdAt: Date };
  messages: Message[];
  experts: Expert[];
  insights: Insight[];
  files: FileType[];
}): string {
  let md = "";

  // Header
  md += `# Farm Friend Roundtable: ${data.conversation.title}\n\n`;
  md += `**Date**: ${format(data.conversation.createdAt, 'yyyy-MM-dd')}\n`;
  md += `**Export Date**: ${format(new Date(), 'yyyy-MM-dd HH:mm:ss')}\n\n`;
  md += "---\n\n";

  // Expert Panel
  md += "## Expert Panel\n\n";
  md += "| Expert | Role | Model |\n";
  md += "|--------|------|-------|\n";
  for (const expert of data.experts) {
    md += `| ${expert.name} | ${expert.role} | ${expert.model} |\n`;
  }
  md += "\n---\n\n";

  // Conversation
  md += "## Conversation\n\n";
  let msgNum = 1;
  for (const message of data.messages) {
    const timestamp = message.timestamp
      ? format(new Date(message.timestamp), 'yyyy-MM-dd HH:mm:ss')
      : 'N/A';

    if (message.userId) {
      md += `### Message ${msgNum} - You (${timestamp})\n\n`;
    } else if (message.expertId) {
      const expert = data.experts.find(e => e.id === message.expertId);
      if (expert) {
        md += `### Message ${msgNum} - ${expert.name} (${expert.role}) (${timestamp})\n\n`;
      }
    }

    md += `${message.content}\n\n`;

    // Artifacts
    if (message.artifacts && message.artifacts.length > 0) {
      md += "#### Artifacts\n\n";
      for (const artifact of message.artifacts) {
        md += formatArtifact(artifact);
      }
    }

    md += "---\n\n";
    msgNum++;
  }

  // Insights
  if (data.insights.length > 0) {
    md += "## Insights\n\n";
    for (const insight of data.insights) {
      md += `### ${insight.title}\n\n`;
      for (const point of insight.points) {
        md += `- ${point}\n`;
      }
      md += "\n";
    }
    md += "---\n\n";
  }

  // File Attachments
  if (data.files.length > 0) {
    md += "## File Attachments\n\n";
    for (const file of data.files) {
      const uploadDate = file.uploadedAt
        ? format(new Date(file.uploadedAt), 'yyyy-MM-dd HH:mm:ss')
        : 'N/A';
      md += `- **${file.filename}** (${file.fileType}) - Uploaded: ${uploadDate}\n`;
    }
    md += "\n";
  }

  md += "---\n\n";
  md += "*Generated by Farm Friend Roundtable*\n";

  return md;
}

function formatArtifact(artifact: Artifact): string {
  let md = `**${artifact.type.toUpperCase()}: ${artifact.title}**\n\n`;

  switch (artifact.type) {
    case "code":
      const lang = artifact.language || "text";
      md += "```" + lang + "\n";
      md += artifact.content + "\n";
      md += "```\n\n";
      break;

    case "json":
      md += "```json\n";
      try {
        const formatted = JSON.stringify(JSON.parse(artifact.content), null, 2);
        md += formatted + "\n";
      } catch {
        md += artifact.content + "\n";
      }
      md += "```\n\n";
      break;

    case "table":
      // Assume content is already markdown table format
      md += artifact.content + "\n\n";
      break;

    case "chart":
      md += `*Chart visualization (data below)*\n\n`;
      md += "```json\n";
      md += artifact.content + "\n";
      md += "```\n\n";
      break;

    case "html":
      md += "```html\n";
      md += artifact.content + "\n";
      md += "```\n\n";
      md += "*Note: Interactive features not available in markdown export*\n\n";
      break;
  }

  return md;
}
